#!/usr/bin/env python

Import('env')
Import('env_modules')

env_alrolib = env_modules.Clone()

# Thirdparty source files

if env['builtin_alrolib']:
    # Build only version 2 for now (as of 2.87)
    thirdparty_dir = "#thirdparty/alrolib/"

    alrolib_src = [
          "rony.cpp",
    ]

    thirdparty_sources = [thirdparty_dir + file for file in alrolib_src]

    env_alrolib.Prepend(CPPPATH=[thirdparty_dir])
    # if env['target'] == "debug" or env['target'] == "release_debug":
    #     env_bullet.Append(CPPFLAGS=['-DBT_DEBUG'])

    env_thirdparty = env_alrolib.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)


# Godot source files
env_alrolib.add_source_files(env.modules_sources, "*.cpp")
