#!/usr/bin/env python

Import('env')
Import('env_modules')

env_intelmoc = env_modules.Clone()

# Thirdparty source files

if env['builtin_intelmoc']:
    # Build only version 2 for now (as of 2.87)
    thirdparty_dir = "#thirdparty/intelmoc/"

    intelmoc_src = [
          #"CompilerSpecific.inl",
          "CullingThreadpool.cpp",
          "intelmoc.cpp",
          "MaskedOcclusionCulling.cpp",
          "MaskedOcclusionCullingAVX2.cpp",
          "MaskedOcclusionCullingAVX512.cpp",
          #"MaskedOcclusionCullingCommon.inl",

    ]

    thirdparty_sources = [thirdparty_dir + file for file in intelmoc_src]

    env_intelmoc.Prepend(CPPPATH=[thirdparty_dir])
    # if env['target'] == "debug" or env['target'] == "release_debug":
    #     env_bullet.Append(CPPFLAGS=['-DBT_DEBUG'])

    env_thirdparty = env_intelmoc.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)


# Godot source files
env_intelmoc.add_source_files(env.modules_sources, "*.cpp")
